use Assignment

select top 1 * from [fact.csv] 
select top 1 * from [Location.csv]
select top 1 * from [Product.csv]

--1. Display the number of states present in the LocationTable.
select count(distinct state) as Numberofstates from [Location.csv]

--2. How many products are of regular type?
select COUNT(distinct Product) from [Product.csv]
where Type='Regular'
--There are 8 products of Regular type

--3. How much spending has been done on marketing of product ID 1?
select sum(cast(Marketing as int)) from [fact.csv] as Totalspend
where ProductId = 1

--4. What is the minimum sales of a product?
select top 1 * from [fact.csv] 
select top 1 * from [Product.csv]

select MIN(sales) as Minsales from 
[fact.csv] F inner join [Product.csv] P on F.ProductId=P.ProductId

--5. Display the max Cost of Good Sold (COGS).
select MAX(COGS) as COGS from [fact.csv]

--6. Display the details of the product where product type is coffee.
select * from [Product.csv] 
where [Product Type]='coffee'

--7. Display the details where total expenses are greater than 40.
select * from [fact.csv]
where [Total Expenses]>40

--8. What is the average sales in area code 719?
select AVG(cast(sales as int)) as AvgSales from [fact.csv]
where [Area Code]='719'

--9. Find out the total profit generated by Colorado state.
select top 1 * from [fact.csv] 
select top 1 * from [Location.csv]

select SUM(cast(Profit as int)) as Profit from 
[fact.csv] F left join [Location.csv] L on F.[Area Code]=L.[Area Code]
where state='Colorado'

--10. Display the average inventory for each product ID.
select F.ProductId, AVG(cast(inventory as int)) as AvgInventory from 
[fact.csv] F inner join [Product.csv] P on F.ProductId=P.ProductId
group by F.ProductId
order by AvgInventory desc

--11. Display state in a sequential order in a Location Table.
select distinct State from [Location.csv]
order by State

--12. Display the average budget of the Product where the average budget margin should be greater than 100.
select ProductId, AVG(cast([Budget Margin] as int)) as AvgBudgetMargin from [fact.csv]
group by ProductId
having AVG(cast([Budget Margin] as int)) > 100

--13. What is the total sales done on date 2010-01-01? 
select SUM(cast(sales as int)) as Totalsales from [fact.csv]
where Date='2010-01-01'

--14. Display the average total expense of each product ID on an individual date.
select [Date], ProductId, AVG(cast([Total Expenses] as int)) as AvgTotExpenses from [fact.csv]
group by Date, ProductId
order by Date

--15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code.
select F.Date, F.ProductId, P.[Product Type], P.Product, F.Sales, F.Profit, L.State, L.[Area Code] from
[fact.csv] F inner join [Location.csv] L on F.[Area Code] = L.[Area Code]
inner join [Product.csv] P on P.ProductId=F.ProductId

--16. Display the rank without any gap to show the sales wise rank.
select * from [fact.csv]
select ProductId, Sales, Dense_rank() over (order by sales desc) as rank from [fact.csv]

--17. Find the state wise profit and sales.
select state, SUM(cast(sales as int)) AS total_sales, SUM(cast(profit as int)) AS total_profit from
[fact.csv] F inner join [Location.csv]  L on F.[Area Code]=L.[Area Code]
GROUP BY State

--18. Find the state wise profit and sales along with the productname.
select state, SUM(cast(sales as int)) as Sales, SUM(cast(profit as int)) as profit, Product from 
[fact.csv] F inner join [Location.csv] L on F.[Area Code]=L.[Area Code]
inner join [Product.csv] P on P.ProductId=F.ProductId
group by State, Product
order by State

--19. If there is an increase in sales of 5%, calculate the increased sales.
select Sales as old_sales, (cast(Sales as float)*1.05) as Increased_sales from [fact.csv]

--20. Find the maximum profit along with the product ID and producttype.
select P.ProductId, P.[Product Type], F.Profit from
[fact.csv] F inner join [Product.csv] P on F.ProductId=P.ProductId
order by F.Profit desc
offset 0 rows 
fetch next 1 rows only

--21. Create a stored procedure to fetch the result according to the product type from Product Table.
create procedure result
@ProductType nvarchar(100)
as
begin
select * from [Product.csv]
where [Product Type]=@ProductType
end

exec result @ProductType = 'coffee'

--22. Write a query by creating a condition in which if the total expenses is less than 60 then it is a profit or else loss.
select ProductId, [Total Expenses],
	case 
        when [Total Expenses] < 60 then 'Profit'
        else 'Loss'
    end as Status
from [fact.csv]

--23. Give the total weekly sales value with the date and product ID details. Use roll-up to pull the data in hierarchical order.
select * from [fact.csv]
select 
    datepart(week, Date) AS SalesWeek,
    year(Date) AS SalesYear,
    ProductID,
    sum(cast(Sales as int)) AS TotalSales
from 
    [fact.csv]
group by datepart(week, Date), year(Date), ProductID
order by SalesYear, SalesWeek, ProductID

--with rollup
select 
    datepart(week, Date) AS SalesWeek,
    year(Date) AS SalesYear,
    ProductID,
    sum(cast(Sales as int)) AS TotalSales
from 
    [fact.csv]
group by datepart(week, Date), year(Date), ProductID
with rollup
order by SalesYear, SalesWeek, ProductID

--24. Apply union and intersection operator on the tables which consist of attribute area code.
--Union:
select [Area Code] from [fact.csv]
union
select [Area Code] from [Location.csv]
--Intersect:
select [Area Code] from [fact.csv]
intersect
select [Area Code] from [Location.csv]

--25. Create a user-defined function for the product table to fetch a particular product type based upon the user’s preference.
create function dbo.FetchProductType(@ProdType nvarchar(255))
returns table
as 
return
(
select ProductID, Product, [Product Type], Type from [Product.csv]
    where [Product Type] = @ProdType
)
select * from dbo.FetchProductType('tea')

--26. Change the product type from coffee to tea where product ID is 1 and undo it.
update [Product.csv]
set [Product Type] = 'Tea'
where ProductId='1'
select * from [Product.csv]

update [Product.csv]
set [Product Type] = 'Coffee'
where ProductId='1'
select * from [Product.csv]
/*--####################################################
declare @TransactionName nvarchar(30) = 'Transact'
begin Transaction @TransactionName
update [Product.csv]
set [Product Type] = 'Tea'
where ProductId='1'
select * from [Product.csv]
rollback transaction @TransactionName
update [Product.csv]
set [Product Type] = 'Coffee'
where ProductId='1'
select * from [Product.csv]
*/

--27. Display the date, product ID and sales where total expenses are between 100 to 200.
select Date, ProductId, Sales from [fact.csv]
where [Total Expenses]  between 100 and 200

--28. Delete the records in the Product Table for regular type.
delete from [Product.csv]
where Type = 'Regular'
select * from [Product.csv]

--29. Display the ASCII value of the fifth character from the column Product.
select ASCII(SUBSTRING(Product,5,1)) as ASCII5thchar from [Product.csv]